; PlatformIO Project Configuration File
; Proyecto: EdgeSecOps (Node Edge M2M + TinyML)
; Hardware: esp32-s3-devkitc-1-n16r8v (16MB Flash, 8MB Octal PSRAM)

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino

; --- CONFIGURACIÓN EXACTA DE HARDWARE (N16R8V) ---
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs

board_build.arduino.memory_type = qio_opi
; --- CONFIGURACIÓN DE PUERTO Y MONITOR ---
monitor_speed = 115200
monitor_filters = 
    esp32_exception_decoder 
    time                    

; --- FLAGS DEL COMPILADOR (C++) ---
build_flags =
    ; Variables de versión (Para el endpoint /api/system/info)
    -D FW_VERSION=\"v1.0.6-production\"
    -D HW_REVISION=\"Rev_B\"
    
    ; Nivel de Logs Nativo (0=Ninguno, 1=Error, 2=Warn, 3=Info, 4=Debug)
    -D CORE_DEBUG_LEVEL=3
    
    ; Credenciales de Emergencia OOBE (Por si falla la NVS)
    -D OOBE_FALLBACK_SSID=\"EdgeNode_Rescate\"

    -D CORE_DEBUG_LEVEL=3       
    -D BOARD_HAS_PSRAM          ; ¡Ahora sí lo podemos activar con seguridad!
    -D ARDUINO_USB_MODE=1       
    -D ARDUINO_USB_CDC_ON_BOOT=1 

    -DCONFIG_CACHE_L1_ICACHE_SIZE=32
    -DCONFIG_CACHE_L1_DCACHE_SIZE=32

; --- DEPENDENCIAS DE LIBRERÍAS ---
lib_deps =
    mathieucarbou/AsyncTCP @ ^3.2.4
    mathieucarbou/ESPAsyncWebServer @ ^3.3.17
    bblanchon/ArduinoJson @ ^7.0.4
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    mobizt/ESP Mail Client @ ^3.4.19
    tanakamasayuki/TensorFlowLite_ESP32 @ ^1.0.0
    plageoj/UrlEncode @ ^1.0.1